# -*- coding: utf-8 -*-
"""final assessment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGkdmG1MAij1c8rwU2U1pNRV-ZzOoSc4
"""

n =int(input())
sum1 = 0
for i in range(1,n):
  if(n % i == 0):
    sum1 = sum1 + i
if (sum1 == n):
  print("the number is perfect number")
else:
  print("the number is not perfect number")